server:
  port: 9000

spring:
  application:
    name: sarafan

  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    initialization-mode: always
#    url: jdbc:mysql://localhost:3306/sarafan_db?createDatabaseIfNotExist=true
#    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/sarafan_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    platform: postgres

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true

  mail:
    host: smtp.yandex.ru
    username: uw@dru.su
    password: 12345678
    port: 465
    protocol: smtps

  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:session_tables.sql

# ===============================
# = SECURITY
# ===============================
security:
  oauth2:
    client:
      clientId: 1090664702599-ea7memu8rbalsdkofpmdmi958l3k1shi.apps.googleusercontent.com
      clientSecret: ${client-secret}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: openid,email,profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    net.lelyak: debug