server:
  port: 9000
  shutdown: graceful

spring:
  application:
    name: sarafan

  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost/sarafan_db
    username: postgres
    password: postgres

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true

  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:session_tables.sql

# ===============================
# = SECURITY
# ===============================
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1090664702599-ea7memu8rbalsdkofpmdmi958l3k1shi.apps.googleusercontent.com
            client-secret: ${client-secret}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:9000/login/oauth2/code/google"
            scope: openid,email,profile
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    net.lelyak: debug
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
